version: '2'
services:
  wallet_db:
    image: mysql:5.7.22
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: apuesta
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: user
      MYSQL_HOST: wallet_db
  wallet_ms:
    build: .
    command: bash -c "sleep 40 && mix ecto.create && mix ecto.migrate && mix phx.server"
    depends_on:
      - wallet_db
    environment:
      PORT: '4004'
      MIX_ENV: 'prod'
